version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    volumes:
      - backend_data:/app
    environment:
      NODE_ENV: development
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend_data:/app
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_data:
  frontend_data:

networks:
  app-network: